#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Добавляет строки меню во все языковые пакеты.

Зачем отдельным скриптом: ключей два десятка, языков шестнадцать, и руками
это превращается в триста строк, где легко пропустить один язык. Здесь
недостающие ключи дописываются, существующие не трогаются.
"""

import io
import json
import os
import sys

LOCALE_DIR = os.path.join('src', 'NekoConverter.App', 'Locale')

TRANSLATIONS = {
    'en': {
        'menu.about_app': 'About NekoConverter',
        'menu.add_files': 'Add Files…',
        'menu.close_window': 'Close Window',
        'menu.copy': 'Copy',
        'menu.cut': 'Cut',
        'menu.edit': 'Edit',
        'menu.file': 'File',
        'menu.help': 'Help',
        'menu.hide': 'Hide NekoConverter',
        'menu.hide_others': 'Hide Others',
        'menu.issues': 'Report an Issue',
        'menu.output_folder': 'Choose Output Folder…',
        'menu.paste': 'Paste',
        'menu.quit': 'Quit NekoConverter',
        'menu.redo': 'Redo',
        'menu.repository': 'GitHub Repository',
        'menu.run': 'Run',
        'menu.select_all': 'Select All',
        'menu.settings': 'Settings…',
        'menu.show_all': 'Show All',
        'menu.toggle_theme': 'Toggle Theme',
        'menu.undo': 'Undo',
        'menu.view': 'View',
    },
    'ru': {
        'menu.about_app': 'О NekoConverter',
        'menu.add_files': 'Добавить файлы…',
        'menu.close_window': 'Закрыть окно',
        'menu.copy': 'Копировать',
        'menu.cut': 'Вырезать',
        'menu.edit': 'Правка',
        'menu.file': 'Файл',
        'menu.help': 'Справка',
        'menu.hide': 'Скрыть NekoConverter',
        'menu.hide_others': 'Скрыть остальные',
        'menu.issues': 'Сообщить о проблеме',
        'menu.output_folder': 'Выбрать папку…',
        'menu.paste': 'Вставить',
        'menu.quit': 'Завершить NekoConverter',
        'menu.redo': 'Повторить',
        'menu.repository': 'Репозиторий на GitHub',
        'menu.run': 'Запуск',
        'menu.select_all': 'Выделить всё',
        'menu.settings': 'Настройки…',
        'menu.show_all': 'Показать все',
        'menu.toggle_theme': 'Сменить тему',
        'menu.undo': 'Отменить',
        'menu.view': 'Вид',
    },
    'zh-Hans': {
        'menu.about_app': '关于 NekoConverter',
        'menu.add_files': '添加文件…',
        'menu.close_window': '关闭窗口',
        'menu.copy': '拷贝',
        'menu.cut': '剪切',
        'menu.edit': '编辑',
        'menu.file': '文件',
        'menu.help': '帮助',
        'menu.hide': '隐藏 NekoConverter',
        'menu.hide_others': '隐藏其他',
        'menu.issues': '报告问题',
        'menu.output_folder': '选择输出文件夹…',
        'menu.paste': '粘贴',
        'menu.quit': '退出 NekoConverter',
        'menu.redo': '重做',
        'menu.repository': 'GitHub 仓库',
        'menu.run': '运行',
        'menu.select_all': '全选',
        'menu.settings': '设置…',
        'menu.show_all': '全部显示',
        'menu.toggle_theme': '切换主题',
        'menu.undo': '撤销',
        'menu.view': '显示',
    },
    'zh-Hant': {
        'menu.about_app': '關於 NekoConverter',
        'menu.add_files': '加入檔案…',
        'menu.close_window': '關閉視窗',
        'menu.copy': '拷貝',
        'menu.cut': '剪下',
        'menu.edit': '編輯',
        'menu.file': '檔案',
        'menu.help': '輔助說明',
        'menu.hide': '隱藏 NekoConverter',
        'menu.hide_others': '隱藏其他',
        'menu.issues': '回報問題',
        'menu.output_folder': '選擇輸出資料夾…',
        'menu.paste': '貼上',
        'menu.quit': '結束 NekoConverter',
        'menu.redo': '重做',
        'menu.repository': 'GitHub 儲存庫',
        'menu.run': '執行',
        'menu.select_all': '全選',
        'menu.settings': '設定…',
        'menu.show_all': '顯示全部',
        'menu.toggle_theme': '切換主題',
        'menu.undo': '還原',
        'menu.view': '顯示方式',
    },
    'ja': {
        'menu.about_app': 'NekoConverter について',
        'menu.add_files': 'ファイルを追加…',
        'menu.close_window': 'ウインドウを閉じる',
        'menu.copy': 'コピー',
        'menu.cut': 'カット',
        'menu.edit': '編集',
        'menu.file': 'ファイル',
        'menu.help': 'ヘルプ',
        'menu.hide': 'NekoConverter を隠す',
        'menu.hide_others': 'ほかを隠す',
        'menu.issues': '問題を報告',
        'menu.output_folder': '出力フォルダを選択…',
        'menu.paste': 'ペースト',
        'menu.quit': 'NekoConverter を終了',
        'menu.redo': 'やり直す',
        'menu.repository': 'GitHub リポジトリ',
        'menu.run': '実行',
        'menu.select_all': 'すべてを選択',
        'menu.settings': '設定…',
        'menu.show_all': 'すべてを表示',
        'menu.toggle_theme': 'テーマを切り替え',
        'menu.undo': '取り消す',
        'menu.view': '表示',
    },
    'ko': {
        'menu.about_app': 'NekoConverter 정보',
        'menu.add_files': '파일 추가…',
        'menu.close_window': '윈도우 닫기',
        'menu.copy': '복사',
        'menu.cut': '오려두기',
        'menu.edit': '편집',
        'menu.file': '파일',
        'menu.help': '도움말',
        'menu.hide': 'NekoConverter 가리기',
        'menu.hide_others': '기타 가리기',
        'menu.issues': '문제 신고',
        'menu.output_folder': '출력 폴더 선택…',
        'menu.paste': '붙여넣기',
        'menu.quit': 'NekoConverter 종료',
        'menu.redo': '실행 취소 복원',
        'menu.repository': 'GitHub 저장소',
        'menu.run': '실행',
        'menu.select_all': '전체 선택',
        'menu.settings': '설정…',
        'menu.show_all': '모두 보기',
        'menu.toggle_theme': '테마 전환',
        'menu.undo': '실행 취소',
        'menu.view': '보기',
    },
    'de': {
        'menu.about_app': 'Über NekoConverter',
        'menu.add_files': 'Dateien hinzufügen…',
        'menu.close_window': 'Fenster schließen',
        'menu.copy': 'Kopieren',
        'menu.cut': 'Ausschneiden',
        'menu.edit': 'Bearbeiten',
        'menu.file': 'Ablage',
        'menu.help': 'Hilfe',
        'menu.hide': 'NekoConverter ausblenden',
        'menu.hide_others': 'Andere ausblenden',
        'menu.issues': 'Problem melden',
        'menu.output_folder': 'Zielordner wählen…',
        'menu.paste': 'Einsetzen',
        'menu.quit': 'NekoConverter beenden',
        'menu.redo': 'Wiederholen',
        'menu.repository': 'GitHub-Repository',
        'menu.run': 'Ausführen',
        'menu.select_all': 'Alles auswählen',
        'menu.settings': 'Einstellungen…',
        'menu.show_all': 'Alle einblenden',
        'menu.toggle_theme': 'Design wechseln',
        'menu.undo': 'Widerrufen',
        'menu.view': 'Darstellung',
    },
    'fr': {
        'menu.about_app': 'À propos de NekoConverter',
        'menu.add_files': 'Ajouter des fichiers…',
        'menu.close_window': 'Fermer la fenêtre',
        'menu.copy': 'Copier',
        'menu.cut': 'Couper',
        'menu.edit': 'Édition',
        'menu.file': 'Fichier',
        'menu.help': 'Aide',
        'menu.hide': 'Masquer NekoConverter',
        'menu.hide_others': 'Masquer les autres',
        'menu.issues': 'Signaler un problème',
        'menu.output_folder': 'Choisir le dossier…',
        'menu.paste': 'Coller',
        'menu.quit': 'Quitter NekoConverter',
        'menu.redo': 'Rétablir',
        'menu.repository': 'Dépôt GitHub',
        'menu.run': 'Exécuter',
        'menu.select_all': 'Tout sélectionner',
        'menu.settings': 'Réglages…',
        'menu.show_all': 'Tout afficher',
        'menu.toggle_theme': 'Changer de thème',
        'menu.undo': 'Annuler',
        'menu.view': 'Présentation',
    },
    'es': {
        'menu.about_app': 'Acerca de NekoConverter',
        'menu.add_files': 'Añadir archivos…',
        'menu.close_window': 'Cerrar ventana',
        'menu.copy': 'Copiar',
        'menu.cut': 'Cortar',
        'menu.edit': 'Edición',
        'menu.file': 'Archivo',
        'menu.help': 'Ayuda',
        'menu.hide': 'Ocultar NekoConverter',
        'menu.hide_others': 'Ocultar otras',
        'menu.issues': 'Informar de un problema',
        'menu.output_folder': 'Elegir carpeta…',
        'menu.paste': 'Pegar',
        'menu.quit': 'Salir de NekoConverter',
        'menu.redo': 'Rehacer',
        'menu.repository': 'Repositorio de GitHub',
        'menu.run': 'Ejecutar',
        'menu.select_all': 'Seleccionar todo',
        'menu.settings': 'Ajustes…',
        'menu.show_all': 'Mostrar todo',
        'menu.toggle_theme': 'Cambiar tema',
        'menu.undo': 'Deshacer',
        'menu.view': 'Visualización',
    },
    'it': {
        'menu.about_app': 'Informazioni su NekoConverter',
        'menu.add_files': 'Aggiungi file…',
        'menu.close_window': 'Chiudi finestra',
        'menu.copy': 'Copia',
        'menu.cut': 'Taglia',
        'menu.edit': 'Modifica',
        'menu.file': 'File',
        'menu.help': 'Aiuto',
        'menu.hide': 'Nascondi NekoConverter',
        'menu.hide_others': 'Nascondi altre',
        'menu.issues': 'Segnala un problema',
        'menu.output_folder': 'Scegli cartella…',
        'menu.paste': 'Incolla',
        'menu.quit': 'Esci da NekoConverter',
        'menu.redo': 'Ripristina',
        'menu.repository': 'Repository GitHub',
        'menu.run': 'Esegui',
        'menu.select_all': 'Seleziona tutto',
        'menu.settings': 'Impostazioni…',
        'menu.show_all': 'Mostra tutto',
        'menu.toggle_theme': 'Cambia tema',
        'menu.undo': 'Annulla',
        'menu.view': 'Vista',
    },
    'pt': {
        'menu.about_app': 'Sobre o NekoConverter',
        'menu.add_files': 'Adicionar arquivos…',
        'menu.close_window': 'Fechar janela',
        'menu.copy': 'Copiar',
        'menu.cut': 'Recortar',
        'menu.edit': 'Editar',
        'menu.file': 'Arquivo',
        'menu.help': 'Ajuda',
        'menu.hide': 'Ocultar NekoConverter',
        'menu.hide_others': 'Ocultar outras',
        'menu.issues': 'Relatar um problema',
        'menu.output_folder': 'Escolher pasta…',
        'menu.paste': 'Colar',
        'menu.quit': 'Encerrar NekoConverter',
        'menu.redo': 'Refazer',
        'menu.repository': 'Repositório no GitHub',
        'menu.run': 'Executar',
        'menu.select_all': 'Selecionar tudo',
        'menu.settings': 'Ajustes…',
        'menu.show_all': 'Mostrar tudo',
        'menu.toggle_theme': 'Alternar tema',
        'menu.undo': 'Desfazer',
        'menu.view': 'Visualizar',
    },
    'pl': {
        'menu.about_app': 'O programie NekoConverter',
        'menu.add_files': 'Dodaj pliki…',
        'menu.close_window': 'Zamknij okno',
        'menu.copy': 'Kopiuj',
        'menu.cut': 'Wytnij',
        'menu.edit': 'Edycja',
        'menu.file': 'Plik',
        'menu.help': 'Pomoc',
        'menu.hide': 'Ukryj NekoConverter',
        'menu.hide_others': 'Ukryj inne',
        'menu.issues': 'Zgłoś problem',
        'menu.output_folder': 'Wybierz folder…',
        'menu.paste': 'Wklej',
        'menu.quit': 'Zakończ NekoConverter',
        'menu.redo': 'Przywróć',
        'menu.repository': 'Repozytorium GitHub',
        'menu.run': 'Uruchom',
        'menu.select_all': 'Zaznacz wszystko',
        'menu.settings': 'Ustawienia…',
        'menu.show_all': 'Pokaż wszystko',
        'menu.toggle_theme': 'Przełącz motyw',
        'menu.undo': 'Cofnij',
        'menu.view': 'Widok',
    },
    'tr': {
        'menu.about_app': 'NekoConverter Hakkında',
        'menu.add_files': 'Dosya Ekle…',
        'menu.close_window': 'Pencereyi Kapat',
        'menu.copy': 'Kopyala',
        'menu.cut': 'Kes',
        'menu.edit': 'Düzen',
        'menu.file': 'Dosya',
        'menu.help': 'Yardım',
        'menu.hide': "NekoConverter'ı Gizle",
        'menu.hide_others': 'Diğerlerini Gizle',
        'menu.issues': 'Sorun Bildir',
        'menu.output_folder': 'Klasör Seç…',
        'menu.paste': 'Yapıştır',
        'menu.quit': "NekoConverter'dan Çık",
        'menu.redo': 'Yinele',
        'menu.repository': 'GitHub Deposu',
        'menu.run': 'Çalıştır',
        'menu.select_all': 'Tümünü Seç',
        'menu.settings': 'Ayarlar…',
        'menu.show_all': 'Tümünü Göster',
        'menu.toggle_theme': 'Temayı Değiştir',
        'menu.undo': 'Geri Al',
        'menu.view': 'Görünüm',
    },
    'ar': {
        'menu.about_app': 'حول NekoConverter',
        'menu.add_files': 'إضافة ملفات…',
        'menu.close_window': 'إغلاق النافذة',
        'menu.copy': 'نسخ',
        'menu.cut': 'قص',
        'menu.edit': 'تحرير',
        'menu.file': 'ملف',
        'menu.help': 'مساعدة',
        'menu.hide': 'إخفاء NekoConverter',
        'menu.hide_others': 'إخفاء الأخرى',
        'menu.issues': 'الإبلاغ عن مشكلة',
        'menu.output_folder': 'اختيار مجلد…',
        'menu.paste': 'لصق',
        'menu.quit': 'إنهاء NekoConverter',
        'menu.redo': 'إعادة',
        'menu.repository': 'مستودع GitHub',
        'menu.run': 'تشغيل',
        'menu.select_all': 'تحديد الكل',
        'menu.settings': 'الإعدادات…',
        'menu.show_all': 'إظهار الكل',
        'menu.toggle_theme': 'تبديل السمة',
        'menu.undo': 'تراجع',
        'menu.view': 'عرض',
    },
    'he': {
        'menu.about_app': 'אודות NekoConverter',
        'menu.add_files': 'הוספת קבצים…',
        'menu.close_window': 'סגירת חלון',
        'menu.copy': 'העתקה',
        'menu.cut': 'גזירה',
        'menu.edit': 'עריכה',
        'menu.file': 'קובץ',
        'menu.help': 'עזרה',
        'menu.hide': 'הסתרת NekoConverter',
        'menu.hide_others': 'הסתרת האחרים',
        'menu.issues': 'דיווח על בעיה',
        'menu.output_folder': 'בחירת תיקייה…',
        'menu.paste': 'הדבקה',
        'menu.quit': 'יציאה מ-NekoConverter',
        'menu.redo': 'ביצוע מחדש',
        'menu.repository': 'מאגר GitHub',
        'menu.run': 'הרצה',
        'menu.select_all': 'בחירת הכול',
        'menu.settings': 'הגדרות…',
        'menu.show_all': 'הצגת הכול',
        'menu.toggle_theme': 'החלפת ערכת נושא',
        'menu.undo': 'ביטול',
        'menu.view': 'תצוגה',
    },
    'sw': {
        'menu.about_app': 'Kuhusu NekoConverter',
        'menu.add_files': 'Ongeza faili…',
        'menu.close_window': 'Funga dirisha',
        'menu.copy': 'Nakili',
        'menu.cut': 'Kata',
        'menu.edit': 'Hariri',
        'menu.file': 'Faili',
        'menu.help': 'Msaada',
        'menu.hide': 'Ficha NekoConverter',
        'menu.hide_others': 'Ficha nyingine',
        'menu.issues': 'Ripoti tatizo',
        'menu.output_folder': 'Chagua folda…',
        'menu.paste': 'Bandika',
        'menu.quit': 'Ondoka NekoConverter',
        'menu.redo': 'Rudia',
        'menu.repository': 'Hifadhi ya GitHub',
        'menu.run': 'Endesha',
        'menu.select_all': 'Chagua zote',
        'menu.settings': 'Mipangilio…',
        'menu.show_all': 'Onyesha zote',
        'menu.toggle_theme': 'Badilisha mandhari',
        'menu.undo': 'Tengua',
        'menu.view': 'Mwonekano',
    },
}


def main():
    changed = 0

    for name in sorted(os.listdir(LOCALE_DIR)):
        if not (name.startswith('strings.') and name.endswith('.json')):
            continue

        code = name[len('strings.'):-len('.json')]
        table = TRANSLATIONS.get(code)

        if table is None:
            print(f'  пропуск: нет перевода для «{code}»', file=sys.stderr)
            continue

        path = os.path.join(LOCALE_DIR, name)

        with io.open(path, encoding='utf-8') as f:
            data = json.load(f)

        added = 0

        for key, value in table.items():
            if key not in data:
                data[key] = value
                added += 1

        if added == 0:
            continue

        ordered = {}
        # Служебные ключи идут первыми, остальные — по алфавиту: так файл
        # читается и диффается одинаково во всех языках.
        for key in ('_name', '_rtl'):
            if key in data:
                ordered[key] = data.pop(key)

        for key in sorted(data):
            ordered[key] = data[key]

        with io.open(path, 'w', encoding='utf-8') as f:
            json.dump(ordered, f, ensure_ascii=False, indent=2)
            f.write('\n')

        print(f'  {code}: +{added} ключей')
        changed += 1

    print(f'\n  обновлено файлов: {changed}')


if __name__ == '__main__':
    main()
